completed testing environment setup
Hackreactor-Quantum-of-Solace/Project-Atelier pull request #12
Opened 2022-12-02 04:34 UTC by MBellinghausen

Environment set up with a dummy test in place that creates a generated snapshot of the render.

2022-12-02 18:51 UTC, bluechocolate2019 requested changes
Questions:
Do we need the commented out sections in App.test.js, or should we delete?

2022-12-02 19:00 UTC, nsfoster87 reviewed
The last file is a little confusing to me and looks like output from a test and I'm assuming we don't want that or any other test output getting checked into git.

2022-12-02 19:00 UTC, nsfoster87 commented on testing/src/App.test.js
> +    // `);
I'm just wondering about the commented out code...I'm assuming it was an attempt at writing an initial test for App component that you didn't want to delete just yet?

2022-12-02 19:00 UTC, nsfoster87 commented on testing/src/App.test.js
> +    // `);
Or is it that we took out the Hello World message from the App component?

2022-12-02 19:00 UTC, nsfoster87 commented on testing/src/__snapshots__/App.test.js.snap
> +`;
I'm not familiar with Jest snapshot, so I'm not quite sure what I'm looking at here...my best guess is that these are files that get outputted from running the tests. If that's the case and we want to use these, I'm assuming this whole folder should not be checked into git, and should be added to the git ignore

2022-12-03 20:13 UTC, bluechocolate2019 approved these changes

2022-12-03 20:13 UTC, merged